//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squeak
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Game_Sessions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Game_Sessions()
        {
            this.T_Game_Session_Players = new HashSet<T_Game_Session_Players>();
        }
    
        public long SessionId { get; set; }
        public string SessionPin { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool SessionIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Game_Session_Players> T_Game_Session_Players { get; set; }
    }
}
