//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Game_Session_Players
    {
        public long Id { get; set; }
        public long SessionId { get; set; }
        public string PlayerName { get; set; }
        public System.DateTime JoinTime { get; set; }
        public string DeviceId { get; set; }
        public string RequestAppId { get; set; }
    
        public virtual T_Game_Sessions T_Game_Sessions { get; set; }
    }
}
